[[redirects]]
  from = "https://confident-darwin-dcaba1.netlify.app"
  to = "https://www.google.com/search?q=anything"
  status = 301
  force = true
  conditions = {Language = ["en","es"], Country = ["US"]}